### ISSUE TITLE
After logging in, Dashboard does not load data. Spinner keeps spinning. 

### ISSUE THREAD

**Issue by mijogu** [mijogu/wheresmyfav#3]
Debug console seems to be pointing towards the getUserData method of UserManagement. 

```
I/flutter (24919): [usermgmt] getUserData for
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): java.lang.IllegalArgumentException: Invalid document reference. Document references must have an even number of segments, but users has 1
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at com.google.firebase.firestore.DocumentReference.zza(com.google.firebase:firebase-firestore@@17.1.1:81)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at com.google.firebase.firestore.FirebaseFirestore.document(com.google.firebase:firebase-firestore@@17.1.1:259)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:92)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:539)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:172)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(24919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (24919): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (24919): PlatformException(error, Invalid document reference. Document references must have an even number of segments, but users has 1, null)
E/flutter (24919): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (24919): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (24919): <asynchronous suspension>
E/flutter (24919): #2      DocumentReference.get (file:///Users/mijogu/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.8.2+3/lib/src/document_reference.dart:75:64)
E/flutter (24919): <asynchronous suspension>
```
yada yada yada

**Comment by mijogu** [comment]
Getting this error now when logged in and there is a Checkin on my Dashboard.

https://photos.app.goo.gl/8BAopVAhWrT8yuHaA

**Comment by iconico** [comment]
The error stemmed from a lot of the auth code using then() instead of await, due to the way it was written there could be problems where the prefs were not set by the time the user came to the homepage.
I did a full refactor of the auth and user library, removing all the then() statements and using async/await throughout. This should fix the issue, I think I got them all.
